
//  FETCH LIST OF DOCUMENTS FOR CURRENT USER IN USER CHAT COLLECTION



// CREATE UPLOAD MESSAGE FUNCTION TO UPLOAD MESSAGE TO USER CHAT COLLECTION

    // PARAMETERS FOR UPLOADING TO USER CHAT COLLECTION
        // SENDER USER ID
        // SENDER USER NAME
        // RECEIVER USER ID
        // RECEIVER USER NAME
        // MESSAGE TEXT
        // TIMESTAMP
        // USER CHAT ID 